### PR TITLE
Added some info about new functions in README

### PR DESCRIPTION
**Pull request by zsszatmari**

### CODE REVIEW

**Comment by leuchtetgruen** [comment]
Hey - I cannot find the functions within the code. can you also add the code changes so I can review them?

**Comment by zsszatmari** [comment]
Hi!

  They were in the other PR you've already accepted some months ago :)

https://github.com/leuchtetgruen/Functional.m/pull/10/files

**Comment by zsszatmari** [comment]
(Or you didn't after all, I just thought, and thus closed it because of that... So please accept both of them. Thanks!)

**Comment by leuchtetgruen** [comment]
Alright - I didnt merge the other pull request before - now I did and I also merged this PR so now both the functions and the docs are merged into master

**Comment by zsszatmari** [comment]
Cool, thanks!

**Pull request merged**
